### ISSUE TITLE
Problem crept in in later version of Moodle

### ISSUE THREAD

**Issue by r0bm1lls** [tlock/moodle-availability_badge#1]
I am using Moodle 3.3. 

Whenever I try and use badge access to restrict access to an activity I get [[error_selectbadge]] after saving the settings

This used to work and is a very useful feature for us. Please help...!

**Comment by Jarvil** [comment]
Hello,

What is the progerss on this?

**Comment by tlock** [comment]
Hi All,

I've fixed the string and error on the master branch.
